# Generated by Django 6.0 on 2025-12-20 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(help_text='Required. Tanzania phone number format: +255XXXXXXXXX', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+255XXXXXXXXX'. Tanzania format required.", regex='^\\+255[67]\\d{8}$')], verbose_name='phone number')),
                ('full_name', models.CharField(help_text='Full legal name of the user', max_length=150, verbose_name='full name')),
                ('role', models.CharField(choices=[('TENANT', 'Tenant'), ('LANDLORD', 'Landlord'), ('AGENT', 'Agent')], default='TENANT', help_text='User role in the platform', max_length=10, verbose_name='role')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user has completed KYC verification.', verbose_name='verified status')),
                ('kyc_status', models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESUBMISSION_REQUIRED', 'Resubmission Required')], default='NOT_SUBMITTED', help_text='Current KYC document verification stage', max_length=25, verbose_name='KYC status')),
                ('email', models.EmailField(blank=True, help_text='Optional email address', max_length=254, null=True, verbose_name='email address')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='profile picture')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['kyc_status'], name='users_kyc_sta_4052e1_idx')],
            },
        ),
    ]
